services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command:
      > # here '>' is block scalar indicator that allows for multi-line strings (command)
      sh -c "python manage.py runserver 0.0.0.0:8000"
